# Generated by Django 3.2.16 on 2023-01-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Femail')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('passenger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='passengers.passenger')),
                ('phone_number', models.BigIntegerField()),
            ],
            bases=('passengers.passenger',),
        ),
    ]
