# Generated by Django 3.2.16 on 2023-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
